enum INPUTS {
  PASSWORD = 'INPUT_TYPE:PASSWORD',
  EMAIL = 'INPUT_TYPE:EMAIL',
  TEXT = 'INPUT_TYPE:TEXT',
  SEARCH = 'INPUT_TYPE:SEARCH',
  USER_NAME = 'INPUT_TYPE:USER_NAME',
}

export default INPUTS;
