enum SCREENS {
  ONBOARDING = 'SCREEN:ONBOARDING',
  SIGN_IN = 'SCREEN:LOGIN',
  SIGN_UP = 'SCREEN:SIGN_UP',
  HOME = 'SCREEN:HOME',
  FAVORITES = 'SCREEN:FAVORITES',
  CHAT = 'SCREEN:CHAT',
  TRENDING = 'SCREEN:TRENDING',
  PROFILE = 'SCREEN:PROFILE',
  HOME_STACK = 'SCREEN:HOME_STACK',
  CART = 'SCREEN:CART',
  MERCHANT = 'SCREEN:MERCHANT',
  SETTINGS = 'SCREEN:SETTINGS',
  SUPPORT = 'SCREEN:SUPPORT',
}

export default SCREENS;
