import { ICard } from '~types';

export const FASHION_PRODUCTS = <ICard[]>[
  {
    merchant_name: 'Fansh Store',
    merchant_rating: 4.7,
    product_name: 'Evening Dress',
    price: 93,
    old_price: 140,
    discount_percentage: 40,
    price_currency: 'USD',
    image: require('../../../../assets/images/fashion/image_1.png'),
  },
  {
    merchant_name: 'Uniqlo Store',
    merchant_rating: 4.5,
    product_name: 'Jacket',
    price: 86,
    old_price: 122,
    discount_percentage: 20,
    price_currency: 'USD',
    image: require('../../../../assets/images/fashion/image_2.png'),
  },
  {
    merchant_name: 'Uniqlo Store',
    merchant_rating: 4.5,
    product_name: 'Evening Dress',
    price: 93,
    old_price: 140,
    discount_percentage: 40,
    price_currency: 'USD',
    image: require('../../../../assets/images/fashion/image_3.png'),
  },
  {
    merchant_name: 'Fansh Store',
    merchant_rating: 4.2,
    product_name: 'Summer jacket',
    price: 40,
    old_price: 120,
    discount_percentage: 60,
    price_currency: 'USD',
    image: require('../../../../assets/images/fashion/image_4.png'),
  },
  {
    merchant_name: 'Fansh Store',
    merchant_rating: 4.7,
    product_name: 'Evening Dress',
    price: 93,
    old_price: 140,
    discount_percentage: 40,
    price_currency: 'USD',
    image: require('../../../../assets/images/fashion/image_5.png'),
  },
  {
    merchant_name: 'Fansh Store',
    merchant_rating: 4.7,
    product_name: 'Evening Dress',
    price: 93,
    old_price: 140,
    discount_percentage: 40,
    price_currency: 'USD',
    image: require('../../../../assets/images/fashion/image_6.png'),
  },
];
